@TravelOrganizer_HostAddress = https://localhost:7187
@BearerToken = ""

POST {{TravelOrganizer_HostAddress}}/api/Auth/register
Content-Type: application/json
{
  "Nome": "João",
  "Sobrenome": "Silva",
  "Email": "joao.silva@example.com",
  "Password": "SenhaForte123!",
  "DataNascimento": "1990-05-15"
}

###

POST {{TravelOrganizer_HostAddress}}/api/Auth/login
Content-Type: application/json
{
  "email": "joao.silva@example.com",
  "password": "SenhaForte123!"
}

###
POST {{TravelOrganizer_HostAddress}}/api/viagens/Criar
Content-Type: application/json
Authorization: Bearer {{BearerToken}}
{
  "UsuarioId": 1,
  "Nome": "Rio de Janeiro",
  "DataInicio": "2025-06-01",
  "DataFim": "2025-06-10",
  "Viajantes": [
    {
      "Nome": "João",
      "Idade": 35,
      "NecessitaAcessibilidade": false
    },
    {
      "Nome": "Maria",
      "Idade": 28,
      "NecessitaAcessibilidade": true
    }
  ]
}
###
GET {{TravelOrganizer_HostAddress}}/api/viagens/Listar
Content-Type: application/json
Authorization: Bearer {{BearerToken}}
